import Head from 'next/head'
import { Inter } from 'next/font/google'
import Banner from '@/Components/Banner'
import Footer from '@/Components/Footer'
import axios from 'axios'
import Produces from '@/Components/Produces'
const inter = Inter({ subsets: ['latin'] })


export default function Home({ data }) {

  return (
    <>
      <Head>
        <title>Main Store Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
    
    
      <div className='position-relative'>
        <Banner />
        <div className=''>
          <div className='container-fluid produces'>
            <div className='row'>
             <Produces Produces={data}/>
             <Footer />
            </div>
          </div>
        </div>
      </div>
    </>
  )
}


// SSR
export async function getServerSideProps() {

  // fetch data 
  let { data } = await axios.get("https://fakestoreapiserver.reactbd.com/tech")
  
  return {
    props: { data }
  }
}

